### ISSUE TITLE
[html bootstrap] design the stats page layout

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/aidre#1]
we need stats like 
- number of issues open
- opened by whom
- title 
- issue body

code only the html layout, we are using bootstrap4

**Comment by msarfrazanwar** [comment]
I want to do this. Can you make requirements more clear?

**Comment by Abdur-rahmaanJ** [comment]
basically we'll fetch issues from github using pygithub

we'll display issues like that.

name

body

see templates/editor.html or templates/index.html to get a feel of how
things work. you don't need to add those {%%} chars etc. just a normal
webpage.

like open issues vs closed issues as pie chart in svg

feel free to think how you can display the four points above

**Comment by German-Corpaz** [comment]
I can work or help on this

**Comment by Abdur-rahmaanJ** [comment]
ok, tinker around break things, learn jinja, feel free, any question PR ^^_

Abdur-Rahmaan Janhangeer
https://github.com/Abdur-rahmaanJ

>

**Comment by Abdur-rahmaanJ** [comment]
finished
